### ISSUE TITLE
Zoom only first element/header of recyclerview?

### ISSUE THREAD

**Issue by amanzan** [gjiazhe/SpringRecyclerView#1]
Great library! Would it be possible to make the zooming effect only for the top-most element of the recyclerview? I'd like to zoom only the "header" when overscrolling

**Comment by gjiazhe** [comment]
Sorry, this library is unable to implement this effect.
It scales the whole recyclerView rather than each itemView.
So maybe you should find out another way to implement this effect.
Thanks for your issue!
